name: Multi-arch Build and Push - msBoilerPlate

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./fitcoach/src/FitCoach.msBoilerPlate
          file: ./fitcoach/src/FitCoach.msBoilerPlate/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/bojewell/fitcoach-msboilerplate:latest
            docker.io/bojewell/fitcoach-msboilerplate:${{ github.sha }}
